version: "3"
services:  
  vendor-portal:
   image: ibrahimshabana/selenium  
   environment:
    - BROWSER
    - HUB_HOST=selenium-hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
   volumes:
   - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
   image: ibrahimshabana/selenium  
   environment:
    - BROWSER
    - HUB_HOST=selenium-hub
    - THREAD_COUNT=3
    - TEST_SUITE=flight-reservation.xml
   volumes:
   - ./output/flight-reservation:/home/selenium-docker/test-output

